# Set the version of docker compose to use
version: '3.9'

# The containers that compose the project
services:
  dev-db:
    image: postgres:14
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: onlinestore